# ############################################################################################################
# APPLICATION-prod : used for production environment
############################################################################################################
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "jdbc:mysql://qeinsights-analyze-dev.mysql.database.azure.com/qeinsights-analyze"
    username: "QEInsightsJavaAnalyze"
    password: "Database@965"

  main:
    additional-java-opts: "-Xmx2048M -Djava.net.preferIPv4Stack=true"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
      # ddl-auto: "validate" when deploying need to use validate
    open-in-view: false
  mail:
    username: ""
    password: ""

flask:
  api:
    java_host: "https://qeinsights-java-dev.azurewebsites.net"
    python_host: "https://qeinsights-python-dev.azurewebsites.net"

apis:
  swagger-url:
    - name: "Analyze Java Spring API docs -PROD"
      url: "https://qeinsights-java-analyze-dev.azurewebsites.net/v2/api-docs"

logging:
  file:
    name: "${logging.file.path}/log.log"
    path: "logs/prod"
server:
  port: 80



