# ############################################################################################################
# NOTE: THIS IS APPLICATION.YAML FOR CHANGES GO TO PROFILE SPECIFIC FILES 
# * * : APPLICATION.YAML IS ONLY USED TO SET DEFAULTS
# * * : PROFILE SPECIFIC FILES ARE USED TO OVERRIDE DEFAULTS
# ############################################################################################################
# APPLICATION-DEV1 : used for local development
# APPLICATION-DEV2 : used for local development
# APPLICATION-TESTING  : used for testing
# APPLICATION-PROD : used for production/ deployment
# ############################################################################################################
spring:
  profiles:
    active: dev1

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none # Default to none for safety, overridden by profile
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 588
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
          connectiontimeout: 5000
          timeout: 5000
          debug: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


logging:
  level:
    root: info
  file:
    path: logs
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

server:
  port: 80